# Generated by Django 3.0.7 on 2020-06-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default='', max_length=100, verbose_name='Place ID slug field'),
            preserve_default=False,
        ),
    ]
