# Generated by Django 3.0.7 on 2020-06-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20200607_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Place ID slug field'),
        ),
    ]
