# Generated by Django 3.0.7 on 2020-08-10 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200810_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.Place', verbose_name='Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Place ID slug field'),
        ),
    ]
